### ISSUE TITLE
Running  python code

### ISSUE THREAD

**Issue by najianasrink** [santhisenan/SDN_DDoS_Simulation#7]
Installed the prerequisites.On running, the topology is up.But PYTHONPATH is not getting.On running the python file "main.py " the following error comes.

najiya@najiya-LIFEBOOK-A514:~/SDN_DDoS_Simulation$ PYTHONPATH=. ryu/bin/ryu-manager main.py
Traceback (most recent call last):
  File "ryu/bin/ryu-manager", line 18, in <module>
    from ryu.cmd.manager import main
  File "/home/najiya/.local/lib/python2.7/site-packages/ryu/cmd/manager.py", line 33, in <module>
    from ryu.app import wsgi
  File "/home/najiya/.local/lib/python2.7/site-packages/ryu/app/wsgi.py", line 23, in <module>
    from tinyrpc.server import RPCServer
  File "/home/najiya/.local/lib/python2.7/site-packages/tinyrpc/__init__.py", line 4, in <module>
    from .protocols import *
  File "/home/najiya/.local/lib/python2.7/site-packages/tinyrpc/protocols/__init__.py", line 15
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

**Comment by santhisenan** [comment]
@najianasrink It seems that you are using python 2. Can you try using python 3?

**Comment by GUO787878** [comment]
@najianasrink Do Tensorflow, Keras, Ryu and Mininet , all of them need to use python3? And Please tell me what the version of Tensorflow and Keras,Thank you very much!

**Comment by BoBoBird-coder** [comment]
the following error comes .Is the PYTHONPATH wrong?

root@ubuntu:/home/bobo-coder/Desktop/ryu/bin# PYTHONPATH=. ryu-manager /home/bobo-coder/Desktop/SDN_DDoS_Simulation/main.py 
loading app /home/bobo-coder/Desktop/SDN_DDoS_Simulation/main.py

File "/home/bobo-coder/Desktop/SDN_DDoS_Simulation/main.py", line 29, in <module>
    from actor_network import ActorNetwork as Actor 
ModuleNotFoundError: No module named 'actor_network'
